### Shows a single product
GET http://localhost:3000/products/2.json

### Shows all products
GET http://localhost:3000/products.json

### Creates a product
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "test_name",
  "price": -10,
  "image_url": "test_url",
  "description": "This description"
}

### Updates a product
PATCH http://localhost:3000/products/1.json
Content-Type: application/json

{
  "price": -10
}

### Deletes a product
DELETE http://localhost:3000/products/19