@jwt = eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2NTMxNTUwMTN9.IpC73TL6rFlo5w2nRDsuIDJjog-aJQLf6qRnkztIP-s

### Shows all orders for a user
GET http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}

### Shows one order for a user
GET http://localhost:3000/orders/3.json
Authorization: Bearer {{jwt}}

### Creates an order for a user
POST http://localhost:3000/orders.json
Authorization: Bearer {{jwt}}
