### Shows a single product
GET http://localhost:3000/products/1.json


### Shows all products
GET http://localhost:3000/products.json?category=Sports

### Creates a product
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "test_name",
  "price": 10,
  "images": ["test_url", "another test", "third test"],
  "description": "This description is a description."
}

### Updates a product
PATCH http://localhost:3000/products/21.json
Content-Type: application/json

{
  "name": "Indoor Basketball"
}

### Deletes a product
DELETE http://localhost:3000/products/20